### ISSUE TITLE
Formatting install directory path

### ISSUE THREAD

**Issue by Spass1966** [bullr/EQAlerter#2]
In Config.py formatting

`EQHOME = "$HOME/EverQuest/"`
or
`EQHOME = "~/EverQuest/"`

results in `FileNotFoundError: [Errno 2] No such file or directory`

What is the correct formatting?

**Comment by bullr** [comment]
You need to specify the full path.  $HOME in bash is an env variable that
returns the full path of the user's home directory.

Ronny
